[build-system]
requires = ["hatchling>=1.21.1"]
build-backend = "hatchling.build"

[project]
name = "osim-viewer"
version = "0.1.0"
description = "A cross-platform OpenSim visualization tool."
readme = "README.md"
requires-python = ">=3.9,<3.13"
authors = [{ name = "Saif Khan", email = "mukh07@dfki.de" }]
license = { text = "MIT" }

dependencies = [
  "opencv-python>=4.7,<5",
  "numpy>=1.23,<2",
  "toml>=0.10,<1",
  "PyQt5>=5.15,<6",
  "pandas",
  "platformdirs>=3,<5",
  "nimblephysics",
  "pyvista>=0.42,<1",
]

[project.urls]
homepage = "https://pc-4501.kl.dfki.de/HMT-V/opensim-viewer"

[project.scripts]
osim-viewer = "osim_viewer.cli:main"
osim-viewer-gui = "osim_viewer.gui:main"

[tool.hatch.build]
packages = ["src/osim_viewer"]
include = [
  "assets/Geometry/**",
]
