[build-system]
requires = ["hatchling>=1.21.1"]
build-backend = "hatchling.build"

[project]
name = "osim-viewer"
version = "0.1.0"
description = "A cross-platform OpenSim visualization tool."
readme = "README.md"
requires-python = ">=3.9,<3.13"
authors = [{ name = "Saif Khan", email = "saifkhichi96@gmail.com" }]
license = { text = "MIT" }

dependencies = [
  "opencv-python>=4.7,<5",
  "numpy>=1.23,<2",
  "toml>=0.10,<1",
  "pyglet>=2.0,<3",
  "platformdirs>=3,<5",
  "nimblephysics",
  "moderngl-window>=2.4.3,<3",
  "moderngl>=5.8.2,<6",
  "imgui==2.0.0",
  "trimesh>=3.9.15,<4",
  "scipy>=1.5.2",
  "Pillow",
  "tqdm>=4.60.0",
]

[project.urls]
homepage = "https://github.com/saifkhichi96/opensim-viewer"

[project.scripts]
osim-viewer = "osim_viewer.cli:main"
osim-viewer-gui = "osim_viewer.gui:main"

[tool.hatch.build.targets.wheel]
packages = ["src/osim_viewer"]

[tool.hatch.build.targets.wheel.force-include]
"assets/Geometry" = "osim_viewer/assets/Geometry"
