znear = 0.01
zfar = 1000.0
camera_zoom_speed = 0.05
window_width = 1600
window_height = 900
fullscreen = false
resizable = true
vsync = true
export_dir = "./export"
playback_fps = 60
scene_fps = 60
run_animations = false
dark_mode = false
shadows_enabled = true
auto_set_floor = true
auto_set_camera_target = true
backface_culling = true
background_color = [1.0, 1.0, 1.0, 1.0]
window_type = "pyglet"
ui_scale = 1.0
z_up = false
